- name: Install and start nginx
  hosts: web
  become: yes # this is = become root. i.e -b
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started