- name: Variables
  hosts: local
  connection: local
  vars: # Play level variables or global level variables
    Course: DEVOPS
    Duration: 120Hrs
    Trainer: "SIVAKUMAR REDDY"
  tasks:
  - name: Variables
    vars: 
      Course: devops # Task level variables, it takes precedence over everything, like task level variables overrides all other vars.
      Duration: 120Hrs
      Trainer: "SIVAKUMAR REDDY"
    ansible.builtin.debug:
      msg: "I have joined {{ Course }} course with a duration of {{ Duration }} and Trainer is {{ Trainer }}"

  - name: variables
    ansible.builtin.debug:
      msg: "I have joined {{ Course }} course with a duration of {{ Duration }} and Trainer is {{ Trainer }}"