- name: variables from files
  hosts: local
  connection: local
  vars_files: # Used to call variables from vars file.
  - course_vars.yaml
  tasks:
  - name: variables from files
    ansible.builtin.debug:
      msg: "I have joined {{ Course }} course with a duration of {{ Duration }} and Trainer is {{ Trainer }}"