- name: Variables
  hosts: local
  connection: local
  vars: # Play level variables or global level variables
    GREET: "Hello from Play level vars"
  vars_files:
  - course_vars.yaml
  vars_prompt:
  - name: GREET
    prompt: Please enter the prompt
    private: false
  tasks:
  - name: Variables
    # vars: 
    #   GREET: "Hello from Task level vars" # Task level vars or local vars
    ansible.builtin.debug:
      msg: "{{ GREET }}"

      # Precedence:
      # 1. Cmd line or ARGS
      # 2. Task level vars