- name: Variables
  hosts: local
  connection: local
  vars:
    number: 10
  tasks:
  - name: print if number is greater than 10
    ansible.builtin.debug:
      msg: "The given number {{ number }} is less than 10"
    when: number > 10