- name: handle undefined variables
  hosts: localhost
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "Hello {{ Person | default('Pradeep') }}"
  
  - name: convert string to lists
    vars:
      fruits: "apple, banana, mango, sapota" # string
    ansible.builtin.debug:
      msg: "The fruits are: {{ fruits | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: SivaKumarReddy
    ansible.builtin.debug:
      msg: "The Course details are: {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - { 'key': 'name', 'value': 'ansible' }
      - { 'key': 'duration', 'value': '10hrs' }
      - { 'key': 'trainer', 'value': 'SivaKumarReddy' }
    ansible.builtin.debug:
      msg: "The course details are : {{ course | items2dict }}"
    
  - name: convert lower to upper
    vars:
      name: "Pradeep Gorle"
    ansible.builtin.debug:
      msg: "My name in lower case is {{ name | lower }}"

  - name: convert upper to lower
    vars:
      name: "Pradeep Gorle"
    ansible.builtin.debug:
      msg: "My name in upper case is {{ name| upper }}"
  
  - name: print min and max number
    vars:
      number: [1,3,5,10,45749,34983040]
    ansible.builtin.debug:
      msg: "The min is {{ number | min }} and max is {{ number| max }}"
  
  - name: Validate the Ip address
    vars: 
      IP: [24757.345.439, 2748.244.333.243, 172.18.32.130]
    ansible.builtin.debug:
      msg: "The correct IP address is : {{ IP | ansible.utils.ipaddr }}"