- name: shell vs command modules
  hosts: local
  connection: local
  tasks:
  - name: execute ls cmd and store the output using shell module
    ansible.builtin.shell: ls -ltr > /tmp/output.txt  # shell modules logs into the server and can use all scripting methods.
  
  # - name: execute ls cmd and store output using command module
  #   ansible.builtin.command: ls -ltr > /tmp/output.txt # This wont work as cmd module cannot login to server and so cant use redirectors.

  - name: execute ls cmd using command module
    ansible.builtin.shell: ls -ltr # This will work as the it is just running the ls -ltr cmd

  - name: execute ls cmd using command module
    ansible.builtin.shell: ls -ltr
    register: prev_cmd_result # Register stores the output to the variable - prev_cmd_result. you can give any variable name.
    ansible.builtin.debug:
      msg: "{{ prev_cmd_result }}"