- name: Create 3 ec2 servers and configure R53 records for them
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-004ca1e37598e62a8
    instance_type: t2.micro
    image_id: ami-09c813fb71547fc4f
    sg_id: sg-0631184d2894a86a3
    zone: pradeepdevops.online
    instances:
    - mysql
    - backend
    - frontend  
  
  tasks:
  - name: Install AWS Python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  
  - name: Creating servers
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ image_id }}"
      security_group: "{{ sg_id }}"
    loop: "{{ instances }}"
    register: ec2_info
  
  # - name: print ec2_info
  #   ansible.builtin.debug:
  #     msg: "EC2 INFO is {{ ec2_info }}"

  - name: print private IP addresses
    ansible.builtin.debug:
      msg: "{{ item.item }}: {{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

  - name: Adding A-Records in R53 for the servers
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item.zone }}"
      type: A
      ttl: 1
      value: "{{ item.instance[0].private_ip_address }}"
      wait: true # This will help waiting till changes are replicated
      override: true # This will override if it the record is already present
