- name: nginx installation
  hosts: all
  become: yes
  serial: 5 #(Play level) This connects to 5 servers and executes a single task and then another 5, after all servers, then next task executes for first 5.
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started


    